### ISSUE TITLE
difference between the -o (save) and -O (archive) flag?

### ISSUE THREAD

**Issue by jphussey05** [ntop/n2disk#44]
What is the difference between the -o (save) and -O (archive) flag? Is there a forum or better place to see answers like this?

**Comment by cardigliano** [comment]
@jphussey05 -o is where PCAP files are stored as soon as they are dumped to disk. There are specific use cases where it is required to move PCAP files to a (usually slower) secondary storage asap, that's when -O is also used.

**Comment by jphussey05** [comment]
So this is passed in addition to -o and facilitates shuttling the PCAP off
local disk to say network attached storage? Is there any prioritization
between the two processes? Currently I’m iowatching the -o directory and
launching a “cleaning script” with each PCAP but the disk competition seems
to be leading to packet drops over time. Was hoping to just move them off
disk with that watcher script but it sounds like -O does the precisely same
thing.

**Comment by cardigliano** [comment]
If you are using HDD (spinning disks), this may be expected as writing and reading/moving files at the same time does not work well due to seeking, besides the IO throughput itself. It is usually not recommended to archive files during busy hours (better overnight when the load is low). The -O option has less priority over the other tasks, however it is not really smart (it does not take into account busy hours), thus a custom script is usually a better option.
